<StartScreen>:
	GridLayout:
		cols: 1
		Label:
			text: 'Start Screen'
		
		# Startscreen Buttons.
		GridLayout:
			cols: 2
			spacing: 50
			padding: 50
			Button:
				size_hint: (None, None)
				width: 300
				height: 125
				text: 'Create an account'
				on_press: root.create_account()
			Button:
				size_hint: (None, None)
				width: 300
				height: 125
				text: 'Have an account, go to login'
				on_press: root.go_to_login()

